---
title: "Economia"
author: Fondazione Cariparma - Osservatorio dei dati sociali
date: last-modified
date-format: "DD-MMMM-YYYY"
lang: it

format:
  html:
    theme: flatly
    code-fold: true
    toc-depth: 3
    toc_float: true
    toc-location: left
    toc-title: Indice
    embed-resources: true
  docx:
    toc: false
    toc-depth: 3
    toc-title: "Indice"
    highlight-style: tango
    embed-resources: true
    page-width: 9
    fig-width: 8
    fig-height: 6
    dpi: 300
execute:
  eval: true
  echo: false
  warning: false
  error: false
  output: false

bibliography: ../CRP_bil_miss.bib
suppress-bibliography: false
---

# Sinloc Analisi di contesto luglio 2025

> LAVORO Dal punto di vista socioeconomico il territorio parmense presenta generalmente un quadro migliore rispetto alla media nazionale; nonostante ciò, permane critica la **forbice occupazionale uomo-donna** e la **disoccupazione giovanile**, più elevata rispetto ai dati regionali

> PRESTAZIONI PENSIONISTICHE La provincia di Parma presenta un importo medio annuo  delle **pensioni superiore** rispetto ai dati nazionali e regionali; tuttavia, la distribuzione per fasce di importo evidenzia una maggiore polarizzazione nei trattamenti pensionistici

> ASSEGNO UNICO UNIVERSALE Parma presenta un importo medio dell’assegno leggermente superiore alla media regionale, ma inferiore a quella nazionale; **i nuclei con figli con disabilità**, percepiscono un importo medio mensile inferiore a quello nazionale e regionale

> CONSULTORI E CENTRI ANTIVIOLENZA Il territorio offre una buona copertura di consultori familiari, garantita anche nei territori periferici; meno presenti invece altri servizi sociali, come spazi dedicati a giovani e donne e centri antiviolenza
  + Nonostante l’elevata presenza di stranieri nel territorio, solo il distretto di Parma offre Spazi per donne immigrate

## Sinloc: Potenziali implicazioni

> 
+ Sostenere l’occupazione inclusiva, soprattutto per donne e persone con background migratorio
+ Promuovere il sostegno a fragilità economiche nascoste (lavoratori poveri, pensionati con basse prestazioni)


# Lula's

same 