---
title: "Servizi sociali - Disabilità"
author: Fondazione Cariparma - Osservatorio dei dati sociali
date: last-modified
date-format: "DD-MMMM-YYYY"
lang: it

format:
  html:
    theme: flatly
    code-fold: true
    toc-depth: 3
    toc_float: true
    toc-location: left
    toc-title: Indice
    embed-resources: true
  docx:
    toc: false
    toc-depth: 3
    toc-title: "Indice"
    highlight-style: tango
    embed-resources: true
    page-width: 9
    fig-width: 8
    fig-height: 6
    dpi: 300
execute:
  eval: true
  echo: false
  warning: false
  error: false
  output: false

bibliography: ../CRP_bil_miss.bib
suppress-bibliography: false
---

# Sinloc Analisi di contesto luglio 2025

+ NON AUTOSUFFICIENZA (1/2)
In totale in Emilia-Romagna vi sono ca. 85.000 persone con limitazioni nelle attività abitualmente svolte, ciò costituisce il 2,3 % della popolazione regionale e risulta il numero più elevato del Nord-Est d’Italia
  + A livello provinciale la disabilità prevale nelle persone anziane

+ NON AUTOSUFFICIENZA (2/2)
L’aumento delle patologie cronico-degenerative e la composizione familiare, che vede sempre
più la presenza di persone anziane spesso sole rispecchiano la necessità di un rafforzamento
della cura alla persona

+ I CAREGIVER FAMILIARI
L’incremento delle situazioni di non autosufficienza, in un contesto di progressivo invecchiamento demografico, comporta una **crescente pressione sui caregiver familiari**, prevalentemente donne, il cui impegno assistenziale supera le 20 ore settimanali in un quarto dei casi

Fonte: 
+ Monitoraggio dei percorsi territoriali per il riconoscimento e il sostegno dei Caregiver Familiari (2021), Rapporto del SSR Emilia-Romagna «Il Sostegno del caregiver in regione Emilia-Romagna» (2020), delle statistiche regionali sulla Popolazione in Emilia-Romagna (2022) e 
+ Articolo di Vita «Giovani caregiver, se il lavoro di cura mette a rischio il futuro» 17.07.2024 (https://www.vita.it/giovani-caregiver-se-il-lavoro-di-cura-mette-a-rischio-il-futuro/)

SERVIZI PER LE PERSONE CON DISABILITÀ
La percentuale di utenti per i servizi destinati alle persone con disabilità è inferiore rispetto a datinazionali; il servizio più utilizzato e con maggiore copertura è quello dell’assistenza domiciliare socio-assistenziale

## Sinloc: Potenziali implicazioni

> 
+ Investire in servizi di cura e sostegno alla non autosufficienza, con particolare attenzione alla domiciliarità


# Lula's

+ Dati citati x caregiver sembrano alquanto vecchi...
+ gia commentato x correzione dati ADI incompleti 


+ Possibili approfondimenti
    + Distinzione in Emilia-Romagna fra competenze AUSL e Comuni - molta ADI è solo sanitaria - per apprezzare la copertura reale. Regione Emilia-Romagna — Rendicontazione [FNA (Fondo Non Autosufficienza)](https://salute.regione.emilia-romagna.it/ssr/organizzazione/fondo-regionale-per-la-non-autosufficienza?utm_source=chatgpt.com)
    + Come viene contabilizzato il servizion SAD nell territorio di Parma, se erogato da Unioni Unioni/Consorzi, e eventuale sottostima di Istat
    + Identificare interventi domiciliari non conteggiati come “SAD”, perchè offerti in modalità diverse indirette (interventi personalizzati distrettuali, contributi per caregiver, ecc.)
      - vedi [ER - Le persone non autosufficienti - Sezione D: l’offerta dei servizi](https://salute.regione.emilia-romagna.it/siseps/reporter/reporter-indicatori/piani-di-zona/persone-non-autosufficienti-offerta-servizi?utm_source=chatgpt.com)

