---
title: "Condizione Abitativa"
author: Fondazione Cariparma - Osservatorio dei dati sociali
date: last-modified
date-format: "DD-MMMM-YYYY"
lang: it

format:
  html:
    theme: flatly
    code-fold: true
    toc-depth: 3
    toc_float: true
    toc-location: left
    toc-title: Indice
    embed-resources: true
  docx:
    toc: false
    toc-depth: 3
    toc-title: "Indice"
    highlight-style: tango
    embed-resources: true
    page-width: 9
    fig-width: 8
    fig-height: 6
    dpi: 300
execute:
  eval: true
  echo: false
  warning: false
  error: false
  output: false

bibliography: ../CRP_bil_miss.bib
suppress-bibliography: false
---

# Sinloc Analisi di contesto luglio 2025

+ CONDIZIONE ABITATIVA (1/2) Il territorio presenta complessivamente un **indice di potenziale fragilità abitativa contenuto**, ad eccezione dei comuni di Parma e Fidenza; sebbene il tasso di sfratti nella provincia sia inferiore alla media nazionale, risulta comunque superiore rispetto a quello regionale

+ CONDIZIONE ABITATIVA (2/2) La provincia di Parma registra una forte domanda di alloggi ERP, con 2.782 domande nel 2022, ma solo il 7,6% di esse è stato soddisfatto, indicando una persistente carenza di alloggi rispetto
alle esigenze abitative della popolazione

## Sinloc: Potenziali implicazioni

> 
+ Politiche di accesso equo alla casa, prevenzione delle fragilità abitative e sviluppo di soluzioni abitative sociali capaci di dare risposte sia a famiglie che a nuovi profili di vulnerabilità (giovani, migranti, anziani soli) 