---
title: "Ambiente"
author: Fondazione Cariparma - Osservatorio dei dati sociali
date: last-modified
date-format: "DD-MMMM-YYYY"
lang: it

format:
  html:
    theme: flatly
    code-fold: true
    toc-depth: 3
    toc_float: true
    toc-location: left
    toc-title: Indice
    embed-resources: true
  docx:
    toc: false
    toc-depth: 3
    toc-title: "Indice"
    highlight-style: tango
    embed-resources: true
    page-width: 9
    fig-width: 8
    fig-height: 6
    dpi: 300
execute:
  eval: true
  echo: false
  warning: false
  error: false
  output: false

bibliography: ../CRP_bil_miss.bib
suppress-bibliography: false
---

# Sinloc Analisi di contesto luglio/dicembre 2025

> AMBIENTE  
> 
> + Parma evidenzia una performance ambientale complessivamente positiva, con alti livelli di raccolta differenziata e buona disponibilità di verde urbano  
> + Persistono tuttavia criticità nei consumi da fonti rinnovabili e nella necessità di ulteriore riduzione delle emissioni  
> + Per quanto riguarda la qualità dell'aria, la città di Parma registra valori positivi, sia rispetto agli altri capoluoghi di provincia dell'Emilia-Romagna, sia rispetto al contesto nazionale 

> AMBIENTE E ECONOMIA CIRCOLARE  e ENERGIA RINNOVABILE 
> 
> + La percentuale di raccolta differenziata nella provincia pari al 79,7% nel 2023, è sostanzialmente rimasta stabile negli ultimi anni, al terzo posto per raccolta differenziata in una regione virtuosa come l’Emilia Romagna, dove il tasso medio di RD è 77,14%  
> + La provincia si assesta su un livello inferiore alla media regionale e nazionale per quanto riguarda i consumi di energia rinnovabile; buona invece la > percentuale di verde urbano disponibile  
 
 


## Sinloc: Potenziali implicazioni

> 
+ Sostenere progetti per efficienza energetica, uso di rinnovabili e riduzione


# Lula's

+ La Dispersione da rete idrica comunale è ~43% (in ER è ~31%) ... perchè? non dovremmo indicarlo 
  + il Goal 6 (“Garantire a tutti la disponibilità e la gestione sostenibile dell'acqua e delle strutture igienico sanitarie”) 